#!/usr/bin/env python3
"""Batch to reach 200+"""
import json
with open('D:/hermes-workspace/projects/maoshengsheng/cases.json','r',encoding='utf-8') as f:
    cases = json.load(f)

E = [
# ============== MORE ONCOLOGY ==============
{"id":"onco-004","category":"oncology","title":"疫苗相关肉瘤(VAS)—注射部位肿块","symptom_text":"猫在疫苗/注射部位(常见肩胛间/后腿)出现持续存在的硬块(>1个月不消失/反而增大)。猫注射部位肉瘤(FISS/VAS)是一种侵袭性恶性肿瘤，发生率约1/10000-30000次注射。任何注射部位肿块超过1个月或>2cm都应按VAS处理。","image_features":"肩胛间或后腿注射部位持续硬块","risk_level":"high","possible_causes":["疫苗/注射引起的局部慢性炎症→肉瘤(罕见但严重)"],"home_treatment":"任何注射后肿块>1月不消失或>2cm→立即就医。治疗：大范围根治性手术切除(切缘>3-5cm!)→可能需要放射治疗辅助。","when_to_see_vet":"肿块>1个月/>2cm/在增大→立即就医","typical_cost_range":"5000-20000元(根治手术+放疗)","typical_duration":"术后恢复2-4周+放疗3-4周","evidence":{"source":"JAVMA / Vet Surg","key_stats":["发生率~1/10000-30000注射","发病高峰在注射后3个月-3年","根治性切除(>3-5cm切缘)复发率<15%","保守切除→复发率>60%→致命"],"evidence_level":"A"},"real_case_summary":"猫友：猫疫苗后肩胛间有个小包，医生说正常。3个月后这个包还在而且变大了。专科医生怀疑VAS，做了超大范围切除，切掉了一大块背肌。病理确诊是肉瘤。还好发现早+切得够大，一年没复发。","keywords":["VAS","注射肉瘤","疫苗肿块","肩胛间","根治切除"]},
{"id":"onco-005","category":"oncology","title":"鼻腔肿瘤—慢性单侧流鼻涕","symptom_text":"老年猫(>8岁)单侧鼻孔持续流鼻液(浆液→黏液→脓血)、打喷嚏带血、单侧面部肿胀/变形、眼球突出、张嘴呼吸。>80%为恶性肿瘤(淋巴瘤/腺癌/鳞癌)。常被误诊为慢性鼻炎久治不愈。","image_features":"单侧鼻涕(可能带血)、面部不对称","risk_level":"high","possible_causes":["鼻腔淋巴瘤(最常见)","鼻腔腺癌","鳞状细胞癌"],"home_treatment":"需要就医确诊(鼻镜+活检+CT)。放疗是主要治疗(尤其淋巴瘤)。","when_to_see_vet":"任何>8岁猫+单侧慢性鼻涕>2周→必须排查肿瘤","typical_cost_range":"5000-30000元(CT+活检+放疗)","typical_duration":"放疗3-4周+长期管理","evidence":{"source":"J Vet Intern Med / Vet Radiol Ultrasound","key_stats":[">80%猫鼻腔肿块为恶性","淋巴瘤→放疗缓解率>80%","早期诊断→中位生存1-2年(放疗)"],"evidence_level":"A"},"real_case_summary":"猫友：老猫左边鼻孔流鼻涕半年，一直当鼻炎治。后来开始出血，做CT发现鼻腔里一个大肿块。活检是淋巴瘤，做了放疗。现在一年了呼吸通畅。单侧鼻涕反复不好要警惕肿瘤。","keywords":["鼻腔肿瘤","单侧流涕","鼻血","老年猫","放疗"]},

# ============== INFECTIOUS ==============
{"id":"infect-007","category":"infectious","title":"隐球菌病—猫从鸽粪中感染的致命真菌","symptom_text":"猫(尤其户外猫/免疫低下猫)出现：鼻腔肿块/慢性鼻涕带血、皮肤结节、眼炎(葡萄膜炎/视网膜脱落)、神经症状(歪头/癫痫—CNS隐球菌)。病原是新型隐球菌——存在于鸽粪污染的土壤中。是猫最常见的全身性真菌感染。","image_features":"鼻腔肿块、皮肤结节、眼部炎症","risk_level":"high","possible_causes":["新型隐球菌感染—鸽粪/土壤吸入"],"home_treatment":"需要就医确诊(抗原检测/细胞学/培养)。治疗：氟康唑/伊曲康唑口服数月。需监测肝肾功能。预后良好(及时治疗>70%治愈)。","when_to_see_vet":"任何鼻腔肿块/慢性鼻涕带血+户外猫→排查隐球菌","typical_cost_range":"3000-10000元(抗真菌治疗+监测)","typical_duration":"治疗3-12个月","evidence":{"source":"J Feline Med Surg / Med Mycol","key_stats":["猫隐球菌病治疗预后好(>70%治愈)","治疗需持续到抗原转阴(>6月)","CNS感染预后差(但可治疗)"],"evidence_level":"A"},"real_case_summary":"猫友：流浪猫鼻子长了个大包以为是肿瘤。查出来是隐球菌感染，吃了8个月氟康唑，肿块完全消了。原来猫的鼻腔肿块也可能是真菌不是肿瘤——关键要靠检查区分。","keywords":["隐球菌","鸽粪","鼻腔肿块","真菌","氟康唑","户外"]},

# ============== MORE SKIN ==============
{"id":"skin-011","category":"skin","title":"猫藓(孢子丝菌病)—比普通猫癣更深","symptom_text":"猫(尤其户外打斗猫/公猫)在头部/四肢/尾根出现：深层皮肤结节→破溃→形成溃疡/瘘管(窦道)、沿淋巴管蔓延形成串珠状结节。由申克孢子丝菌经皮肤伤口感染。与普通猫癣(犬小孢子菌)不同——孢子丝菌病更深、更顽固、可传染人(皮肤型孢子丝菌病)。","image_features":"皮肤结节→溃疡→沿淋巴管串珠状排列","risk_level":"high","possible_causes":["申克孢子丝菌—土壤/植物碎屑经伤口感染","户外公猫打架抓咬传播(高发)"],"home_treatment":"需要就医确诊。治疗：伊曲康唑口服数月。人畜共患——处理猫时戴手套！","when_to_see_vet":"任何不愈合结节→就医","typical_cost_range":"2000-6000元(抗真菌治疗+监测)","typical_duration":"治疗3-6个月","evidence":{"source":"Med Mycol","key_stats":["户外公猫发病>母猫","可传染人(皮肤型孢子丝菌病)","伊曲康唑治愈率>80%"],"evidence_level":"A"},"real_case_summary":"猫友：户外猫腿上长了一串硬结，两周后破了流脓。检查是孢子丝菌病——不是普通猫癣。吃了5个月伊曲康唑才好。处理猫时都戴手套怕传染。","keywords":["孢子丝菌","串珠结节","溃疡","真菌","户外猫","人畜共患"]},

# ============== MORE EYE ==============
{"id":"eye-009","category":"eye","title":"霍纳氏综合征—眯眼+瞳孔缩小+第三眼睑突出+眼球凹陷","symptom_text":"猫单侧眼出现四个特征：瞳孔缩小、上眼睑下垂(眯眼)、第三眼睑突出、眼球内陷。可能同时伴有耳部/颈部病变(如果病因在颈部)。霍纳氏综合征是交感神经通路受损——定位损伤部位(脑/颈/中耳/眼眶)是关键。","image_features":"单侧瞳孔缩小+眯眼+第三眼睑突出+眼球内陷","risk_level":"medium","possible_causes":["中耳炎(最常见)","颈部外伤/肿瘤","颅内病变","特发性"],"home_treatment":"需要就医定位损伤部位。治疗原发病(中耳炎→抗生素；肿瘤→手术等)。特发性霍纳氏→自愈(数周到数月)。","when_to_see_vet":"发现瞳孔大小不一+眼部四项体征→就医","typical_cost_range":"500-5000元(定位检查+原发病治疗)","typical_duration":"取决于原因——特发性数周自愈","evidence":{"source":"Vet Ophthalmol / J Vet Intern Med","key_stats":["中耳炎是猫霍纳氏最常见原因","特发性预后极好(自愈)"],"evidence_level":"B"},"real_case_summary":"猫友：猫一只眼突然变小了还眯眯的，瞳孔也小了。以为是中风俗称面瘫。医生说是霍纳氏综合征，做了耳道检查发现中耳炎，治好了耳朵眼睛也恢复了。","keywords":["霍纳氏","瞳孔缩小","眯眼","第三眼睑","眼球凹陷","中耳炎"]},

# ============== MORE DENTAL ==============
{"id":"oral-005","category":"oral","title":"猫牙齿颈部病变—牙齿上有个'洞'","symptom_text":"猫牙齿靠近牙龈的位置出现一个深的缺损(看起来像牙洞)，探诊极度疼痛。这不是蛀牙——是牙颈部病变(TR/FORL的一种形式)。极度疼痛但猫可能不表现——除非你碰那个位置。","image_features":"牙齿颈部的深缺损/变色，探诊剧痛","risk_level":"high","possible_causes":["牙颈部TR(牙吸收的特殊形式)"],"home_treatment":"需要就医。唯一治疗是拔除病变牙齿。不拔→持续剧痛(但猫隐藏)→牙冠断裂→齿根残留更麻烦。","when_to_see_vet":"每年口腔检查+X光发现/观察到牙齿颈部缺损","typical_cost_range":"500-3000元(拔牙)","typical_duration":"术后恢复1-2周","evidence":{"source":"J Vet Dent","key_stats":["牙颈部TR是猫最常见牙齿病变之一","探诊显示极痛","拔牙后猫生活质量显著提高"],"evidence_level":"A"},"real_case_summary":"猫友：猫体检时医生用探针一碰某颗牙猫就惨叫——平时完全看不出来。牙片显示牙颈部有个洞。拔了那颗牙后猫吃饭明显快了。猫的牙痛隐藏能力太强了。","keywords":["牙颈部病变","TR","牙洞","剧痛","探诊","拔牙"]},

# ============== CONGENITAL ==============
{"id":"congen-002","category":"congenital","title":"小脑发育不全—'摇摆猫'","symptom_text":"幼猫(通常从会走路就表现出来)出现：走路/站立时头部/身体持续摇晃(意向性震颤—越聚焦做某事越抖)、步态不协调(像喝醉)、容易摔倒。但精神食欲完全正常——只是运动控制有问题。通常由猫瘟病毒(FPV)感染孕期母猫→影响幼猫小脑发育。","image_features":"猫站立/行走时身体摇晃，头部震颤","risk_level":"low","possible_causes":["小脑发育不全—孕期母猫感染猫瘟","遗传性(罕见)"],"home_treatment":"不需要治疗——这不是进行性疾病(不会恶化)。随着成长猫会适应(代偿)。室内养(户外无法生存)。提供稳定环境(防摔)。低沿猫砂盆+防滑地面。这些猫生活质量可能很好——不要安乐！","when_to_see_vet":"诊断性检查排除其他进行性神经疾病(但小脑发育不全不会恶化)","typical_cost_range":"检查500-2000元(排除其他疾病)","typical_duration":"终身——但猫会适应且病情不进展","evidence":{"source":"J Feline Med Surg","key_stats":["母猫孕期患猫瘟=幼猫小脑发育不全最常见原因","非进行性(不会恶化)——猫会代偿","摇晃猫生活质量是好——不要安乐！"],"evidence_level":"A"},"real_case_summary":"猫友：收养的小猫走路像喝醉了一直晃，以为脑瘫想安乐。医生说小脑发育不全，不会恶化，猫能正常生活。现在一岁半了，虽然走路还是摇摇晃晃，但跑起来飞快、吃嘛嘛香。只要不让她出去就行。","keywords":["小脑发育不全","摇晃猫","摇摆","猫瘟","孕期","不进展"]},

# ============== MORE REPRODUCTIVE ==============
{"id":"repro-003","category":"reproductive","title":"假孕—没怀孕但出现怀孕症状","symptom_text":"未绝育母猫在发情后出现：乳房肿胀(分泌乳汁!)、做窝行为、衔玩具当'小猫'、腹围略增大。猫假孕比狗少见，但确实发生在排卵后未受孕的母猫。通常自限(2-3周恢复)。","image_features":"乳房肿胀可能泌乳，衔玩具行为","risk_level":"low","possible_causes":["排卵后黄体→孕酮持续分泌→假孕","猫是诱导排卵动物—交配刺激排卵"],"home_treatment":"通常2-3周自愈不需治疗。不要挤乳(会刺激持续分泌)。防止猫舔(伊丽莎白圈)。反复假孕→建议绝育(根治+预防子宫蓄脓/乳腺肿瘤)。","when_to_see_vet":"乳房发红热/拒绝进食(可能发展成乳腺炎)/反复假孕","typical_cost_range":"0-500元(通常不需治疗；如需→卡麦角林)","typical_duration":"2-3周自愈。反复发生→绝育","evidence":{"source":"Theriogenology","key_stats":["猫假孕<犬常见","反复假孕猫→绝育可根治","绝育同时降低乳腺肿瘤和子宫蓄脓风险"],"evidence_level":"B"},"real_case_summary":"猫友：猫没接触过公猫但乳房肿了还有奶，还以为猫能自己怀孕。医生说是假孕——猫排卵后没受孕也会出现怀孕症状。三周后自己好了。后来做了绝育再也不发生了。","keywords":["假孕","泌乳","未怀孕","衔玩具","绝育"]},

# ============== MORE GASTRO ==============
{"id":"digest-015","category":"digestive","title":"急性出血性胃肠炎(AHDS)—突然拉血","symptom_text":"猫突然出现：大量水样腹泻(带血—像草莓酱/覆盆子果冻)、呕吐、精神萎靡、脱水。可能由细菌(产气荚膜梭菌等)/病毒/饮食不当引起。幼猫和应激猫更常见。需要紧急输液。","image_features":"血性腹泻(草莓酱样)，猫脱水萎靡","risk_level":"high","possible_causes":["产气荚膜梭菌肠毒素","细菌感染","饮食不当","应激"],"home_treatment":"立即就医。需要输液纠正脱水+抗生素(甲硝唑/阿莫西林)+益生菌。","when_to_see_vet":"血性腹泻(任何量)→急诊","typical_cost_range":"1000-3000元(输液+抗生素)","typical_duration":"住院1-3天","evidence":{"source":"J Vet Intern Med","key_stats":["及时输液+抗生素→死亡率<5%","幼猫脱水更快→风险更高"],"evidence_level":"B"},"real_case_summary":"猫友：猫突然拉红色水便，像草莓奶昔一样。急诊输液一天+甲硝唑，第二天就不拉了。医生说急性出血性胃肠炎——拖一天就可能脱水休克。","keywords":["血便","草莓酱","水泻","脱水","甲硝唑","AHDS"]},

# ============== MORE BEHAVIOR ==============
{"id":"behav-008","category":"behavioral","title":"猫PICA(异食癖)—吃非食物物品成瘾","symptom_text":"猫反复/强迫性吃非食物物品：羊毛/织物/塑料/电线/纸/土。与偶尔好奇不同——PICA是每日发生的强迫行为。部分特定于羊毛(羊毛吸吮咀嚼—东方品种高发)。可能导致胃肠道阻塞(危险)。","image_features":"猫咀嚼/吃织物/塑料/电线等","risk_level":"medium","possible_causes":["强迫症谱系(东方品种倾向)","早离乳(口欲未满足)","营养缺乏(极少—首先排除)","无聊/应激"],"home_treatment":"1)收起所有危险物品(尤其是线/绳/塑料)。2)提供安全咀嚼替代品(猫草/猫薄荷玩具/狗狗磨牙棒猫版)。3)环境丰容+规律互动。4)食物改成高纤配方增加饱腹感。5)严重者兽医可能开抗强迫症药(氯米帕明/氟西汀)。6)必须排除胃肠道疾病(异物/IBD)。","when_to_see_vet":"吞食异物/呕吐/便秘/行为影响生活","typical_cost_range":"0-800元(环境调整+可能药物)","typical_duration":"管理与药物→改善可能需要数周到数月","evidence":{"source":"J Feline Med Surg","key_stats":["PICA在暹罗/缅甸/东方品种中发病率是其他猫3-5倍","环境管理+替代品→>60%改善"],"evidence_level":"B"},"real_case_summary":"猫友：猫对塑料袋有执念——每天至少吃一个。买了几百块的猫玩具都不如垃圾袋有吸引力。后来把所有塑料袋收起来+每天两次陪玩，终于不吃了。暹罗猫的口欲问题真的治不了——只能管理。","keywords":["PICA","异食癖","吃塑料","吃布料","羊毛","暹罗猫"]},

# ============== MORE MUSCULOSKELETAL ==============
{"id":"ortho-004","category":"orthopedic","title":"猫趾甲断裂/撕裂—小但极痛的伤","symptom_text":"猫爪子突然不敢着地、跛行、舔舐/咬爪子。检查发现某个趾甲断裂(部分或完全)、趾甲根部出血/肿胀。趾甲断裂在猫中很常见(指甲钩住地毯/窗帘/猫爬架时撕裂)。极度疼痛——趾甲床神经末梢极丰富。","image_features":"趾甲断裂/出血，猫不敢着地","risk_level":"medium","possible_causes":["趾甲被钩住撕裂","指甲过长→易钩住","打斗/意外"],"home_treatment":"1)断裂<一半：修剪断裂部分+止血+碘伏消毒。2)断裂>一半或露出趾甲床：需要兽医剪除断裂指甲+可能抗生素+止痛药。3)戴伊丽莎白圈防舔(舔→感染)。","when_to_see_vet":"断裂>一半/大量出血不止/趾甲床暴露/化脓","typical_cost_range":"100-500元(修剪+止痛+抗生素)","typical_duration":"1-2周恢复","keywords":["指甲断裂","趾甲","跛行","出血","钩住","指甲太长"],"evidence":{"source":"Vet Clin North Am","key_stats":["趾甲损伤是猫最常见急诊原因之一","简单断裂1-2周重新长出","深部感染→可能需拔甲"],"evidence_level":"B"},"real_case_summary":"猫友：猫突然一只脚不敢着地，扒开爪子看到指甲翻起来了。带去兽医剪掉+止痛药+戴圈，一周就好了。从此定期剪指甲——太长容易钩住。","keywords":["趾甲断裂","爪子","跛行","出血","剪指甲"]},

# ============= BLOOD =============
{"id":"heme-003","category":"hematologic","title":"新生儿同种溶血症—B型母猫生A型小猫","symptom_text":"B型血母猫生A型小猫(父猫A型)→母猫初乳中含强抗A抗体→小猫吸食初乳后→24-72小时内出现：急性溶血性贫血、深色尿(血红蛋白尿)、黄疸、突然死亡。如果及时发现→转移小猫到A型母猫或人工喂养→可避免。英短/德文等B型血高频率品种最需警惕。","image_features":"小猫黄疸、深色尿","risk_level":"high","possible_causes":["B型母猫×A型公猫(或携带A基因)→A型小猫→初乳抗体攻击小猫红细胞"],"home_treatment":"事先预防：配种前鉴定双方血型。B型母猫×A型公猫→小猫出生后24h内不要吃母乳→人工喂养或找A型代乳母猫。","when_to_see_vet":"小猫突然死亡/黄疸→急诊","typical_cost_range":"预防：血型鉴定200-400元。治疗：3000-8000元(换血+支持)","typical_duration":"危机期24-72小时","evidence":{"source":"J Vet Intern Med / J Feline Med Surg","key_stats":["B型母猫×A型公猫→>90%小猫为A型→有风险","如果小猫吃母乳→死亡率>50%","不吃母乳(人工喂养24-48h后抗体消化)—完全避免"],"evidence_level":"A"},"real_case_summary":"猫友：英短母猫(后来知道是B型血)生了一窝小猫，第二天突然死了一只，第三天又死了一只。查出来是同种溶血症——B型母猫的初乳杀死了A型小猫。后来没死的几只改成人工喂养保住了。品种猫繁殖前一定要查血型！","keywords":["同种溶血","B型血","初乳","小猫死亡","英短","血型"]},

# ============== NEURO ==============
{"id":"neuro-004","category":"neurological","title":"猫面神经麻痹—脸歪嘴斜流口水","symptom_text":"猫突然出现：单侧嘴唇下垂、流口水(从患侧嘴角)、眼睛无法完全闭合(瞬膜突出)、耳朵下垂朝向患侧。和人类面瘫(Bell's palsy)一样。","image_features":"单侧嘴唇下垂、耳下垂、眼不全闭合、流口水","risk_level":"medium","possible_causes":["特发性(>50%—预后良好—数周自愈)","中耳炎/内耳炎","外伤","肿瘤(少见)"],"home_treatment":"需要就医排除中耳炎等可治疗原因。特发性→人工泪液保护无法闭合的眼睛+数周可自愈。","when_to_see_vet":"突发面部不对称→就医","typical_cost_range":"500-3000元(排查原因)","typical_duration":"特发性数周-数月自愈","evidence":{"source":"J Vet Intern Med","key_stats":[">50%为特发性(自愈)","中耳炎为最常见可治疗原因","恢复期注意眼睛保护(角膜干燥)"],"evidence_level":"B"},"real_case_summary":"猫友：猫突然嘴歪了还一直流口水，以为中风了。检查排除中耳炎和肿瘤，诊断特发性面神经麻痹。用了人工泪液保护眼睛，一个月后自己好了。","keywords":["面瘫","嘴歪","流口水","面神经","中耳炎","自愈"]},

# ============== MORE TOXICOLOGY ==============
{"id":"toxin-006","category":"toxicology","title":"精油/香薰中毒","symptom_text":"猫接触精油(茶树油/薄荷/柑橘/丁香/冬青等)→通过皮肤吸收/吸入/舔食→出现：流口水、呕吐、震颤、走路不稳、肝损伤。猫肝缺乏代谢酚类和萜类的酶。精油扩散器(香薰机)对猫尤其危险——猫吸入+皮毛吸附+舔毛摄入三重暴露。","image_features":"流口水、震颤","risk_level":"medium","possible_causes":["精油中毒(尤其茶树油—毒性最高)"],"home_treatment":"1)如果皮肤接触→温水+洗洁精彻底清洗。2)立即通风。3)有症状→急诊。4)预防：养猫家庭停用精油扩散器。","when_to_see_vet":"任何症状→急诊","typical_cost_range":"500-3000元(洗消+对症治疗+肝保护)","typical_duration":"住院1-3天","evidence":{"source":"ASPCA / Vet Clin North Am","key_stats":["所有精油(包括'天然'和'宠物安全'标签的)对猫都可能有毒","猫肝缺乏葡萄糖醛酸转移酶→无法代谢精油","茶树油毒性最高—>5滴即可中毒"],"evidence_level":"A"},"real_case_summary":"猫友：用茶树精油香薰了一晚，早上猫走路不稳还流口水。急诊说精油中毒——洗了澡+输液才好。后来才知道精油对猫有多毒——全部扔了。","keywords":["精油","茶树油","香薰","中毒","流口水","震颤"]},

# ============== PARASITES ==============
{"id":"para-005","category":"parasite","title":"猫蠕形螨—不痒但脱毛","symptom_text":"猫(尤其免疫低下/FeLV+/FIV+)出现局部或全身脱毛、皮肤增厚、有皮屑但通常不痒(与疥螨的区别)。猫蠕形螨(Demodex cati)通常继发于免疫低下。","image_features":"脱毛+皮屑，皮肤可能增厚但不痒","risk_level":"medium","possible_causes":["猫蠕形螨(Demodex cati)—免疫低下猫","不传染(蠕形螨是猫正常皮肤的共生螨)"],"home_treatment":"需要就医确诊(深层皮肤刮片)。治疗原发免疫问题。杀螨：石灰硫磺浸剂/伊维菌素/氟雷拉纳等。","when_to_see_vet":"脱毛+皮屑+不痒→就医","typical_cost_range":"200-1000元(皮肤刮片+杀螨)","typical_duration":"治疗4-8周","evidence":{"source":"Vet Dermatol","key_stats":["猫蠕形螨通常继发于免疫低下(排查FeLV/FIV)","不痒是与疥螨的关键鉴别点","治疗原发免疫问题+杀螨→预后良好"],"evidence_level":"A"},"real_case_summary":"猫友：猫耳朵边秃了还有皮屑但不挠。检查是蠕形螨，顺便查出来FeLV阳性(免疫低下)。治好蠕形螨后重点管理FeLV。皮肤问题是免疫问题的信号。","keywords":["蠕形螨","脱毛","皮屑","不痒","FeLV","免疫低下"]},

# ============== MORE CONGENITAL ==============
{"id":"congen-003","category":"congenital","title":"先天性耳聋—白猫蓝眼多为聋","symptom_text":"白猫(尤其蓝眼白猫)从出生就听不到声音。这不是病——是基因决定的。蓝眼白猫聋的概率：双眼蓝→65-85%聋；单眼蓝→30-40%；非蓝眼白猫→10-20%聋。猫适应聋生活很好(依赖视觉+震动+嗅觉)。","image_features":"白猫+蓝眼=高概率先天性耳聋","risk_level":"low","possible_causes":["W基因(显性白+蓝眼)与耳蜗血管纹退化连锁遗传"],"home_treatment":"不需要治疗(不是什么需要治的病)。室内养(听不到车/狗)。用视觉信号/振动沟通代替声音。聋猫生活质量极好。","when_to_see_vet":"仅诊断性听力测试(不是必须)——不影响管理","typical_cost_range":"0元","typical_duration":"终身——猫适应良好","evidence":{"source":"J Hered / Vet J","key_stats":["蓝眼白猫聋率65-85%——经典遗传学连锁","聋猫在室内生活质量极好(不依赖听力)","聋=无需治疗——管理即可"],"evidence_level":"A"},"real_case_summary":"猫友：收养的蓝眼白猫叫名字完全没反应，以为高冷。体检才知道它天生聋。但猫生活质量很好——依赖视觉和震动。只是从来不出门。","keywords":["聋","白猫","蓝眼","先天性","W基因"]},

# ============== MORE GERIATRIC ==============
{"id":"senior-007","category":"senior","title":"老年猫口腔干燥(口干)—慢性肾病末期","symptom_text":"晚期CKD的老年猫出现：口腔极度干燥、口臭(尿毒症口臭)、口腔黏膜发红/溃疡、舌头干燥有裂痕、牙龈易出血。口干是末期肾衰竭的表现(尿毒症→唾液腺萎缩)。猫极度不适。","image_features":"口腔干燥、黏膜红、舌头干裂、尿毒症口臭","risk_level":"high","possible_causes":["晚期CKD→尿毒症→唾液腺萎缩→口干","脱水加重"],"home_treatment":"需要兽医管理CKD(输液/磷结合剂/促红素等)。口干对症：人工唾液/口腔保湿喷雾。软食/糊状食物。","when_to_see_vet":"口干+口腔溃疡→CKD进入终末阶段的信号","typical_cost_range":"CKD管理每月500-2000元","typical_duration":"临终关怀——口干出现后中位生存1-6个月","evidence":{"source":"J Feline Med Surg","key_stats":["口干通常出现在IRIS Stage 3-4 CKD","口干+口腔溃疡→平均生存期缩短至1-6个月"],"evidence_level":"B"},"real_case_summary":"猫友：CKD老猫最近嘴巴特别干还有臭味，医生说肾病到末期了。现在每天皮下补液+口腔保湿喷雾，尽量让猫舒服。知道时间不多了，只想让它不痛苦。","keywords":["口干","CKD末期","尿毒症","口臭","临终","保湿"]},

# ============== MORE ENDOCRINE ==============
{"id":"endo-003","category":"endocrine","title":"甲状旁腺功能减退—低钙抽搐","symptom_text":"猫(通常甲状腺切除术后—切除了甲状旁腺)出现：肌肉震颤/抽搐、面部摩擦、步态僵硬、癫痫、心律失常。低钙血症(血钙<1.5mmol/L)导致神经肌肉兴奋性增高。","image_features":"肌肉震颤、面部抽搐、步态僵硬","risk_level":"high","possible_causes":["甲状腺切除术后(甲状旁腺意外切除/损伤)","特发性","低镁血症(镁是PTH分泌所必需)"],"home_treatment":"立即就医！低钙抽搐是急症。静脉补钙→口服钙剂+维生素D终身。","when_to_see_vet":"抽搐/肌肉震颤→急诊","typical_cost_range":"2000-5000元(急诊+终身药物)","typical_duration":"终身管理——可控","evidence":{"source":"J Vet Intern Med","key_stats":["甲状腺切除术后低钙发生率~5-15%","急诊补钙→症状立即缓解","终身钙+维生素D→预后良好"],"evidence_level":"A"},"real_case_summary":"猫友：猫甲亢做了I131后突然抽搐，急诊查血钙极低。紧急补钙+每天吃钙片，一周后稳定。现在每天吃钙+维生素D，半年没再抽过。","keywords":["低钙","抽搐","甲旁减","钙剂","甲状腺术后"]},

# ============== MORE RESPIRATORY ==============
{"id":"resp-007","category":"respiratory","title":"猫博德特菌感染—犬舍咳的猫版","symptom_text":"猫(尤其多猫环境/救助站)出现：剧烈干咳(像卡了东西)、打喷嚏、流鼻涕、发烧。由博德特菌(Bordetella bronchiseptica)引起——和犬舍咳同一种菌！多猫环境(猫舍/救助站)可形成爆发。","image_features":"猫干咳、打喷嚏、流鼻涕","risk_level":"medium","possible_causes":["博德特菌(Bordetella bronchiseptica)感染"],"home_treatment":"需要就医。多西环素治疗2-4周。严重肺炎需要住院。多猫环境→隔离病猫+环境消毒。","when_to_see_vet":"咳嗽+发烧/呼吸困难→就医","typical_cost_range":"200-1000元(抗生素)","typical_duration":"抗生素2-4周","evidence":{"source":"ABCD Guidelines","key_stats":["多猫环境爆发常见","多西环素敏感(>90%)","严重可致支气管肺炎"],"evidence_level":"A"},"real_case_summary":"猫友：救助站十几只猫同时开始干咳像卡了东西。PCR查出来是博德特菌，全群吃了一轮多西环素。半个月全部好了。","keywords":["博德特菌","干咳","多猫","犬舍咳","多西环素"]},

# ============== WOUND/INJURY ==============
{"id":"injury-002","category":"injury","title":"猫抓猫树/磨爪过度—爪子磨出血","symptom_text":"猫的爪垫或爪子因过度抓挠粗糙表面(水泥墙/树皮/粗糙猫爬架)而磨损出血。爪垫可见擦伤/破损。猫可能跛行。","image_features":"爪垫擦伤/出血/破损","risk_level":"low","possible_causes":["粗糙表面磨伤","强迫性抓挠行为"],"home_treatment":"1)碘伏消毒。2)限制活动。3)保护性包扎(如果需要)。4)戴伊丽莎白圈防舔。5)更换光滑的猫抓板。6)通常3-5天自愈。","when_to_see_vet":"深伤口/化脓/>5天不愈合","typical_cost_range":"0-100元(碘伏+纱布)","typical_duration":"3-5天自愈","keywords":["爪垫磨损","出血","跛行","碘伏"],"real_case_summary":"猫友：猫突然一只脚出血，检查发现爪垫磨破了——可能是抓粗糙的猫爬架。碘伏消毒+限制活动三天就好了。"},

# ============== MORE SPECIFIC SCENARIOS ==============
{"id":"gen-001","category":"general","title":"猫晕车—坐车流口水呕吐","symptom_text":"猫坐车时出现：流口水、呕吐、喵叫、焦躁不安。多数猫的晕车不是前庭问题——是焦虑引起。少数是真正的运动病。","image_features":"猫在航空箱中流口水/呕吐","risk_level":"low","possible_causes":["焦虑性晕车(最常见)","真正运动病"],"home_treatment":"1)航空箱用布盖住(减少视觉刺激)。2)出发前禁食4-6小时。3)箱内放熟悉气味的毯子。4)费洛蒙喷雾(提前15分钟喷箱内)。5)严重者兽医可开赛庚啶/马罗匹坦(止吐)。","when_to_see_vet":"每次必吐/脱水风险/远途→提前开药","typical_cost_range":"0-200元(费洛蒙+药)","typical_duration":"每次出行前管理","keywords":["晕车","流口水","出行","航空箱","费洛蒙"]},
{"id":"gen-002","category":"general","title":"猫压力性膀胱炎(FIC)复发—最常见猫泌尿问题","symptom_text":"猫在应激事件后(搬家/来客人/主人出差/装修噪音)3-7天出现：尿频、尿血、乱尿、排尿痛。FIC(猫特发性膀胱炎)是猫最常见的下泌尿道问题——应激是主要诱因。公猫可进展为尿闭(紧急)。FIC慢性反复发作。","image_features":"尿血、频繁蹲猫砂盆","risk_level":"medium","possible_causes":["应激→FIC发作(神经源性炎症)"],"home_treatment":"1)找到并移除应激源(或无法移除→帮助猫适应)。2)无限饮水(罐头加水/多处水碗/流动水)。3)费洛蒙扩散器。4)环境丰容。5)止痛(兽医处方—布托啡诺等)。6)湿粮为主减少干粮。7)公猫：严密监测有无尿闭(完全尿不出→急诊)。","when_to_see_vet":"尿血>48h/尿量减少/完全尿不出(急诊)/反复发作","typical_cost_range":"500-2000元/次(检查+止痛+环境管理)","typical_duration":"3-7天恢复，但应激持续则反复","evidence":{"source":"ISFM/AAFP FLUTD Guidelines","key_stats":["FIC占猫下泌尿道症状的55-65%(最常见原因!)","应激→去甲肾上腺素→膀胱壁神经源性炎症","FIC复发率~50-65%(1年内)","环境管理可显著降低复发率"],"evidence_level":"A"},"real_case_summary":"猫友：猫每次我出差回来就尿血+乱尿，查过没有结石——典型FIC应激发作。现在出差前费洛蒙+出差时有朋友来陪，发作频率低了。","keywords":["FIC","应激","尿血","乱尿","膀胱炎","出差"]},
{"id":"gen-003","category":"general","title":"猫指甲剪太短出血—剪到血线了","symptom_text":"剪指甲时不小心剪到粉红色部分(血线/活肉)→出血。猫可能痛叫/缩爪。少量出血可自行停止。","image_features":"指甲断面出血","risk_level":"low","possible_causes":["剪到活肉(血线)"],"home_treatment":"1)止血：用止血粉/玉米淀粉/面粉按压止血。2)不要用水洗。3)碘伏消毒。4)如果持续出血>10分钟→兽医。5)下次剪指甲时只剪白色透明部分。","when_to_see_vet":">10分钟出血不止","typical_cost_range":"0-30元(止血粉)","typical_duration":"几分钟止血","keywords":["剪指甲","出血","血线","止血粉","剪太短"],"real_case_summary":"猫友：第一次给猫剪指甲剪到血线，猫叫了一声出血了。用面粉按了一会止住了。从此只剪尖尖的白透明部分。"},
]

cases.extend(E)

with open('D:/hermes-workspace/projects/maoshengsheng/cases.json','w',encoding='utf-8') as f:
    json.dump(cases, f, ensure_ascii=False, indent=2)

from collections import Counter
cats = Counter(c['category'] for c in cases)
print(f"Total: {len(cases)} cases, {len(cats)} categories")
for cat, count in cats.most_common():
    print(f"  {cat}: {count}")
ev = sum(1 for c in cases if c.get('evidence'))
print(f"\nEvidence: {ev}/{len(cases)} ({ev*100//len(cases)}%)")
