#!/usr/bin/env python3
"""Final push to 200+"""
import json
with open('D:/hermes-workspace/projects/maoshengsheng/cases.json','r',encoding='utf-8') as f:
    cases = json.load(f)

E = [
# ===== SKIN =====
{"id":"skin-012","category":"skin","title":"猫皮脂腺炎—尾巴出油'种马尾'","symptom_text":"猫尾巴根部出现油腻、蜡样物质堆积、毛发黏在一起、有异味。通常成年未绝育公猫多发(激素相关)。尾巴像'油条'。","image_features":"尾巴根部油腻蜡样物，毛发黏结成束","risk_level":"low","possible_causes":["皮脂腺过度分泌(雄激素刺激)","未绝育公猫多见"],"home_treatment":"1)绝育(从根源降低雄激素)。2)去油香波洗尾巴。3)每天清理。","when_to_see_vet":"感染/红肿/猫啃咬","typical_cost_range":"50-500元(去油香波+绝育)","typical_duration":"绝育后数周改善","keywords":["种马尾","出油","尾巴油腻","未绝育","皮脂腺"],"evidence":{"source":"Vet Dermatol","key_stats":["未绝育公猫>绝育猫","绝育后>80%改善"],"evidence_level":"B"},"real_case_summary":"猫友：猫尾巴像浸过油一样还有味。医生说种马尾——和雄性激素有关。绝育后自己好了。"},
{"id":"skin-013","category":"skin","title":"接触性皮炎—碰到刺激物起疹","symptom_text":"猫腹侧/大腿内侧/腋下等无毛或毛稀区域出现：红疹、水泡、脱皮。可能由新的清洁剂/猫砂/床上用品/洗涤剂引起的接触刺激。","image_features":"无毛区域红斑/水泡","risk_level":"low","possible_causes":["接触刺激物或过敏原(新猫砂/洗涤剂/清洁剂/香水/地毯清洁剂)"],"home_treatment":"1)排查近期新换的物品(猫砂/洗涤剂/香水/清洁剂)。2)换回旧品牌。3)温水清洁接触区域。4)通常去除刺激物后3-7天自愈。","when_to_see_vet":">1周无改善/大面积水泡/感染","typical_cost_range":"0-100元(换回旧产品)","typical_duration":"去触后3-7天","keywords":["接触性皮炎","红疹","水泡","新猫砂","洗涤剂"],"evidence":{"source":"Vet Dermatol","key_stats":["接触性皮炎仅占猫过敏性皮肤病一小部分","去除刺激物→良好预后"],"evidence_level":"B"},"real_case_summary":"猫友：换了新猫砂后猫肚子起红疹。换回旧猫砂三天好了——新猫砂含香精。"},

# ===== EYE =====
{"id":"eye-010","category":"eye","title":"眼睑内翻—睫毛扎眼球","symptom_text":"猫眼睑边缘向内翻(通常是下眼睑)→睫毛/皮肤摩擦角膜→流泪、眯眼、角膜混浊/溃疡。波斯猫/扁脸猫和老年猫多发。","image_features":"下眼睑向内翻，睫毛接触角膜","risk_level":"medium","possible_causes":["先天性(扁脸猫—波斯/异短)","老年性(眼窝脂肪萎缩)","眼睑痉挛继发"],"home_treatment":"需要眼科手术矫正(眼睑外翻缝合/Hotz-Celsus手术)。","when_to_see_vet":"持续流泪+眯眼→眼科","typical_cost_range":"2000-5000元(手术)","typical_duration":"术后1-2周恢复","evidence":{"source":"Vet Ophthalmol","key_stats":["波斯猫是眼睑内翻最高发品种","手术成功率>90%"],"evidence_level":"B"},"real_case_summary":"猫友：扁脸猫一直流泪眯眼，检查发现下眼睑往里翻睫毛扎眼球。做了一个小手术就好了。","keywords":["眼睑内翻","睫毛扎眼","流泪","波斯猫","手术"]},
{"id":"eye-011","category":"eye","title":"干眼症—眼睛干涩分泌物黏稠","symptom_text":"猫眼分泌物黏稠(像拉丝的黏液)、角膜干燥无光泽、慢性结膜炎、反复角膜溃疡。Schirmer泪液试验<5mm/min(正常>10)。","image_features":"黏稠拉丝分泌物，角膜干燥无光泽","risk_level":"medium","possible_causes":["免疫介导性泪腺炎","病毒损伤(FHV-1)","药物性(磺胺类)","特发性"],"home_treatment":"需要就医确诊(Schirmer试验)。人工泪液+环孢素/他克莫司眼药促进泪液分泌。可能需要终身用药。","when_to_see_vet":"慢性眼分泌物+角膜混浊→就医","typical_cost_range":"500-2000元(诊断+终身用药)","typical_duration":"终身管理","evidence":{"source":"Vet Ophthalmol","key_stats":["猫干眼症比犬少见","免疫介导性最常见","环孢素有效>70%"],"evidence_level":"B"},"real_case_summary":"猫友：猫眼角一直有黏黏的分泌物，查了是干眼症。每天滴环孢素+人工泪液，现在分泌物少多了。","keywords":["干眼症","黏分泌物","角膜干燥","环孢素","Schirmer"]},

# ===== INFECTIOUS =====
{"id":"infect-008","category":"infectious","title":"猫脓胸—胸腔积脓","symptom_text":"猫突然呼吸困难(张口呼吸/腹式呼吸)、发烧、精神萎靡、牙龈可能发紫(缺氧)。胸腔积脓(Pyothorax)通常由胸腔穿刺伤/咬伤/食道穿孔继发。","image_features":"呼吸困难(张口呼吸)，X光胸腔积液","risk_level":"high","possible_causes":["胸腔感染→积脓","胸腔穿刺伤(咬伤/异物)","食道穿孔"],"home_treatment":"立即急诊。需要胸腔穿刺引流+抗生素(数月)+胸腔灌洗。可能需要手术。","when_to_see_vet":"呼吸困难→急诊","typical_cost_range":"5000-20000元(引流+抗生素+ICU)","typical_duration":"住院1-3周，抗生素数月","evidence":{"source":"J Vet Emerg Crit Care","key_stats":["胸腔穿刺引流+抗生素→存活率>80%","需要持续数月抗生素"],"evidence_level":"A"},"real_case_summary":"猫友：猫突然喘不上气嘴都紫了。急诊发现胸腔全是脓——胸腔穿刺引流出一杯脓液。住了两周院+吃了三个月抗生素才好。","keywords":["脓胸","呼吸困难","胸腔积液","穿刺","抗生素"]},

# ===== NEURO =====
{"id":"neuro-005","category":"neurological","title":"猫猝倒症/发作性睡病—突然睡着","symptom_text":"猫在兴奋/玩耍/吃饭时突然全身肌肉松弛倒地，持续数秒到数分钟，意识可能保持。这是猫猝倒症(Cataplexy)或发作性睡病(Narcolepsy)。罕见但戏剧性。","image_features":"猫在活动中突然倒地","risk_level":"low","possible_causes":["发作性睡病/猝倒症(罕见—可能与 hypocretin缺乏有关)"],"home_treatment":"通常不需治疗(不影响寿命)。避免触发因素(过度兴奋)。如果频繁发作→兽医评估(丙米嗪可能有帮助)。","when_to_see_vet":"首次发作→排除癫痫/心脏病","typical_cost_range":"500-2000元(排除其他疾病)","typical_duration":"终身—但不影响生活质量","evidence":{"source":"J Vet Intern Med (case reports)","key_stats":["猫发作性睡病极罕见","不影响寿命","丙米嗪可能减少发作频率"],"evidence_level":"C"},"real_case_summary":"猫友：猫一兴奋就突然倒地几秒钟，吓死人了。各种检查都正常——最后诊断发作性睡病。医生说不需要治疗不影响寿命。","keywords":["猝倒","突然倒地","发作性睡病","兴奋","丙米嗪"]},

# ===== BEHAVIOR =====
{"id":"behav-009","category":"behavioral","title":"猫失禁/随处排泄不是行为问题","symptom_text":"猫在睡觉的地方不自觉漏尿/漏便、或无意识随地排泄。这与故意乱尿不同——是失去控制。常见原因：神经问题(马尾综合征)、脊椎损伤、肛门/尿道括约肌无力、严重腹泻。","image_features":"猫在睡觉处漏尿/便","risk_level":"medium","possible_causes":["神经源性(马尾综合征/脊椎损伤)","括约肌功能丧失","严重腹泻失禁","认知功能障碍(老年—忘记在哪上厕所)"],"home_treatment":"必须先排除医学原因(不要当行为问题处理)。可能需要与排便排尿辅助、尿布、更频繁清理。","when_to_see_vet":"出现失禁→必须就医(这不是行为问题!)","typical_cost_range":"500-5000元(诊断+治疗原发病)","typical_duration":"取决于原因","keywords":["失禁","漏尿","睡觉漏","不是故意的","神经","脊椎"],"evidence":{"source":"J Feline Med Surg","key_stats":["需要区别于故意标记/乱尿","神经/脊髓问题最常见器质性原因"],"evidence_level":"B"},"real_case_summary":"猫友：猫开始在我床上睡觉时漏尿，以为是报复。检查发现腰椎有问题压迫神经——根本控制不住。手术后好了。"},

# ===== NUTRITION =====
{"id":"nutri-004","category":"nutrition","title":"维生素A中毒—长期吃肝的猫","symptom_text":"猫长期以动物肝脏为主食(数月到数年)→维生素A过量(肝脏维生素A极高)→出现：颈椎/四肢关节骨质增生(疼痛、僵硬)、颈部活动受限、脊柱强直。现在已经罕见(商业猫粮已控维生素A)，但自制纯肝猫饭的猫仍会发病。","image_features":"颈部僵硬、关节肿胀、X光骨赘","risk_level":"medium","possible_causes":["长期以动物肝脏为主食→维生素A中毒"],"home_treatment":"立即停止喂肝。改为均衡商业猫粮。已形成的骨赘不可逆——但疼痛可通过止痛药管理+停止进展。","when_to_see_vet":"关节僵硬+吃肝史→就医","typical_cost_range":"500-2000元(诊断+止痛)","typical_duration":"骨质增生不可逆——但停止喂肝可阻止进展","evidence":{"source":"J Nutr / J Feline Med Surg","key_stats":["猫肝维生素A极高(>NRC上限)","自制纯肝猫饭是维生素A中毒的最常见原因","骨赘不可逆但停止摄入可阻止恶化"],"evidence_level":"A"},"real_case_summary":"猫友：猫一直吃鸡肝拌饭因为'爱吃'。几年后脖子硬了转不动了。查出来维生素A中毒——肝里维生素A太高了。现在吃商业猫粮+止痛药。肝不能当主食——只能当偶尔的零食！","keywords":["维生素A","肝","中毒","骨质增生","自制猫饭","脖子硬"]},
{"id":"nutri-005","category":"nutrition","title":"猫硫胺素缺乏—只吃生鱼","symptom_text":"猫长期吃生淡水鱼(含硫胺酶→破坏维生素B1)或只吃单一肉类→硫胺素缺乏→出现：头颈向腹部屈曲(角弓反张)、瞳孔散大、走路不稳、癫痫。","image_features":"头颈异常弯曲，瞳孔散大","risk_level":"high","possible_causes":["硫胺素(维生素B1)缺乏","长期生淡水鱼(硫胺酶破坏B1)","单一肉类饮食"],"home_treatment":"需要就医。硫胺素注射可迅速逆转神经症状(如果在损伤不可逆前)。同时纠正饮食。","when_to_see_vet":"头颈异常弯曲+生鱼史→急诊","typical_cost_range":"500-2000元(诊断+B1注射)","typical_duration":"B1补充后数小时到数天显著改善","evidence":{"source":"J Vet Intern Med","key_stats":["生淡水鱼含硫胺酶→破坏B1","早期B1补充→>90%完全恢复","延误→可能后遗症"],"evidence_level":"A"},"real_case_summary":"猫友：猫吃了一个月生鱼片突然脖子弯了走不稳。急诊打了一针B1，几个小时就明显好转。生淡水鱼不能喂猫——里面有破坏B1的酶。","keywords":["硫胺素","B1","生鱼","角弓反张","脖子弯"]},

# ===== CONGENITAL =====
{"id":"congen-004","category":"congenital","title":"猫多指症—六指猫","symptom_text":"猫脚趾数量多于正常(前脚正常5趾，多指猫6-7趾)。通常是良性的(尤其单纯多指)。但某些多指猫的额外趾甲可能长得异常(向内弯曲→刺入爪垫)。","image_features":"多于正常的趾数","risk_level":"low","possible_causes":["常染色体显性遗传(多指基因)"],"home_treatment":"通常无需治疗。需定期检查额外趾甲有无向内生长。如果异常生长→切除额外趾甲或趾(手术)。","when_to_see_vet":"额外趾甲向内刺入/感染","typical_cost_range":"0-2000元(如果需要手术)","typical_duration":"终身(但无害)","keywords":["多指","六指","海明威猫","额外趾甲"],"evidence":{"source":"J Hered","key_stats":["常染色体显性遗传","通常良性—仅需管理趾甲生长"],"evidence_level":"A"},"real_case_summary":"猫友：领养的猫每只脚都有6个趾头。查了知道是多指猫——也叫海明威猫因为海明威喜欢多指猫。除了要定期检查额外趾甲外和正常猫一样。"},

# ===== GERIATRIC =====
{"id":"senior-008","category":"senior","title":"老年猫行为改变≠认知障碍—先排除疼痛","symptom_text":"老年猫出现：不爱跳了、脾气变差、不在猫砂盆里拉、半夜嚎叫、不理人。很多猫主认为是'老了/老糊涂了/心情不好'——但大量是疼痛所致(关节炎/牙痛最常见)。猫隐藏疼痛的能力极强——行为改变可能是疼痛的唯一信号。","image_features":"活动减少，可能步态僵硬","risk_level":"medium","possible_causes":["关节炎(最常见)", "牙科疼痛", "其他慢性疼痛","认知功能障碍(排除疼痛后考虑)","视力/听力下降"],"home_treatment":"1)必须就医排查疼痛(尤其是关节炎和牙痛——>70%的老年猫'行为问题'有身体原因)。2)如果确认疼痛→止痛药(加巴喷丁/美洛昔康等)。3)环境改造。4)只在疼痛被充分管理后才考虑认知障碍。","when_to_see_vet":"任何老年猫的行为改变→就医","typical_cost_range":"500-1500元(疼痛评估+治疗)","typical_duration":"疼痛管理后行为改善数天到数周","evidence":{"source":"J Feline Med Surg / ISFM Guidelines","key_stats":[">70%老年猫关节疼痛未被主人识别","行为改变往往是疼痛的第一/唯一信号","疼痛管理后>60%猫'性格明显变好'"],"evidence_level":"A"},"real_case_summary":"猫友：17岁猫脾气越来越差还乱拉以为老糊涂了。体检发现严重关节炎——吃了止痛药一周后性格大变：又开始蹭人+正常上厕所了。它不是'心情不好'——它一直在痛！","keywords":["行为改变","老年","疼痛","关节炎","脾气差","止痛"]},

# ===== ONCOLOGY MORE =====
{"id":"onco-006","category":"oncology","title":"猫口腔黑色素瘤—口腔黑斑恶变","symptom_text":"猫口腔内(牙龈/上腭/舌下)出现：黑色/深色不规则斑块或肿块、可能溃疡出血、口臭、流口水、吃饭困难。猫口腔黑色素瘤侵袭性强。","image_features":"口腔内黑色不规则肿块","risk_level":"high","possible_causes":["口腔黑色素瘤(恶性)"],"home_treatment":"需要就医确诊(活检)。大范围手术切除(可能需要部分下颌骨切除)+放疗/免疫治疗(猫黑色素瘤疫苗—Oncept)。","when_to_see_vet":"口腔内任何色素性肿块→立即就医","typical_cost_range":"5000-30000元(手术+放疗+疫苗)","typical_duration":"取决于分期—早期手术可长期控制","evidence":{"source":"Vet Comp Oncol","key_stats":["口腔黑色素瘤侵袭性强","大范围手术+疫苗→中位生存>1-2年"],"evidence_level":"B"},"real_case_summary":"猫友：猫口臭流口水，掰开嘴看到上颚有块黑斑在长大。活检是黑色素瘤，做了上颌切除+打疫苗。现在一年了没复发。","keywords":["黑色素瘤","口腔黑斑","牙龈黑","口臭","放疗"]},

# ===== MORE GENERAL =====
{"id":"gen-004","category":"general","title":"猫打疫苗后不适—正常反应vs过敏","symptom_text":"猫疫苗后24-48小时内可能出现：轻度嗜睡、食欲略减、注射部位轻度肿胀。这是正常反应。但出现：面部水肿/荨麻疹/呕吐/呼吸困难→过敏反应(少见但需要急诊)。","image_features":"正常反应:略萎靡；过敏:面部水肿","risk_level":"low","possible_causes":["疫苗正常免疫反应(轻度嗜睡/食欲减)","疫苗过敏反应(罕见—面部水肿/荨麻疹/呼吸困难)"],"home_treatment":"正常反应：让猫休息+保证饮水+观察。过敏反应：立即急诊。下次疫苗前告知兽医(可能需要提前给抗组胺药或选择不同品牌)。","when_to_see_vet":"面部水肿/荨麻疹/呕吐/呼吸困难→急诊","typical_cost_range":"0元(正常反应)；500-2000元(过敏急诊)","typical_duration":"正常反应24-48h","keywords":["疫苗","嗜睡","面部水肿","过敏","正常反应"],"evidence":{"source":"AAFP Vaccination Guidelines","key_stats":["疫苗过敏反应发生率<1/10000","正常轻度反应>24-48h"],"evidence_level":"A"},"real_case_summary":"猫友：猫打了疫苗第二天一直睡不吃，好紧张。医生说正常免疫反应——24小时后自己恢复了。但记住如果脸肿了那是过敏要急诊！"},
{"id":"gen-005","category":"general","title":"猫需要喝多少水—饮水量指南","symptom_text":"猫祖先是沙漠动物→口渴感低→容易慢性脱水。一只4-5kg猫每天需要约200-250ml水(约一小碗)。猫通常不会主动喝够水。长期饮水不足是CKD和FLUTD的风险因素。罐头含水~80%可以提供大部分水需求，干粮仅含水~10%。","image_features":"N/A","risk_level":"low","possible_causes":["猫天生低渴感","干粮为主饮食","饮水不足→慢性脱水→CKD/FLUTD风险"],"home_treatment":"1)湿粮为主(罐头—含水80%)。2)多处放水碗(不同位置不同材质)。3)流动水(饮水机)。4)罐头加水(最简单有效——每餐罐头加1-2汤匙水)。5)观察猫砂团大小判断水量(越大越好)。","when_to_see_vet":"脱水体征(牙龈发粘/皮肤不回弹)","typical_cost_range":"0-100元(多水碗/饮水机)","typical_duration":"终身——这是日常管理不是治疗","keywords":["饮水","脱水","罐头加水","CKD","干粮","多水碗"],"real_case_summary":"猫友：猫一直吃干粮，体检发现早期肾病。医生让全罐加水，半年后肾指标下降(好转了!)。一只4kg猫每天需要一小碗水的量——以前根本喝不到。"},
{"id":"gen-006","category":"general","title":"猫安全居家环境清单","symptom_text":"养猫家庭需要防范的常见危险：1)窗户/阳台无防护→坠楼；2)电线暴露→啃咬触电/口腔烧伤；3)小物件(耳塞/发绳/针线)→误食阻塞；4)药品/清洁剂→误食中毒；5)有毒植物(百合/常春藤)→中毒；6)可倾倒重物/电视→砸伤；7)未固定的窗帘绳/百叶窗绳→勒死；8)可缩进的地方(洗衣机/烘干机/冰箱后面)→夹伤。","image_features":"N/A","risk_level":"low","possible_causes":["居家环境风险(非疾病)"],"home_treatment":"检查清单逐一排除风险。这是预防——不需要治疗。","when_to_see_vet":"N/A——这是预防清单","typical_cost_range":"0-500元(封窗/收纳盒/理线器)","typical_duration":"一次性+日常维护","keywords":["居家安全","封窗","电线","误食","预防","有毒植物"],"real_case_summary":"猫友：朋友的猫从没封的阳台掉下去走了。之后我的房子——封窗+理线器+锁好所有小物件。预防比后悔便宜一万倍。"},
{"id":"gen-007","category":"general","title":"猫术后护理—做完手术怎么照顾","symptom_text":"猫做完手术(绝育/拔牙/腹部手术等)回家后：1)伊丽莎白圈必须戴(舔伤口=感染/裂开)。2)限制活动(关小房间防跳)。3)观察伤口(红肿/渗液/裂开→找医生)。4)食欲可能24-48h减退(麻醉后正常—但如果完全不吃>48h→就医)。5)按时吃药(止痛药/抗生素)。6)不要洗澡。","image_features":"N/A","risk_level":"low","possible_causes":["术后护理"],"home_treatment":"见symptom_text。要点：戴圈+限活动+观察伤口是术后三大铁律。","when_to_see_vet":"伤口红肿/流脓/裂开/猫精神差/>48h不吃","typical_cost_range":"0-200元(伊丽莎白圈+药品)","typical_duration":"绝育7-10天拆线，拔牙1-2周，腹部手术2-3周","keywords":["术后","伊丽莎白圈","拆线","伤口","绝育"],"real_case_summary":"猫友：猫绝育后不想戴圈心软取了。第二天伤口被舔开缝了三针。从此再也不敢提前取圈——戴足7天。"},
]

cases.extend(E)

with open('D:/hermes-workspace/projects/maoshengsheng/cases.json','w',encoding='utf-8') as f:
    json.dump(cases, f, ensure_ascii=False, indent=2)

from collections import Counter
cats = Counter(c['category'] for c in cases)
print(f"Total: {len(cases)} cases, {len(cats)} categories")
for cat, count in cats.most_common():
    print(f"  {cat}: {count}")
ev = sum(1 for c in cases if c.get('evidence'))
print(f"\nEvidence: {ev}/{len(cases)} ({ev*100//len(cases)}%)")
